<template>
    <v-app>
        <v-main class="bg">
            <div class="app">
                <div class="orientation-portrait">
                    <img src="./assets/orientation.svg" class="orientation-logo">
                </div>

                <div class="normal orientation-landscape">
                    <ModalWindow />
                    <router-view />
                </div>


            </div>
        </v-main>
    </v-app>
</template>


<script setup>
import ModalWindow from '@/components/menu/ModalWindow.vue'
import ACE from '@/components/ace/ACE.vue'
</script>


<style lang="scss">
  /* Use Roboto for the dashboard, Open Sans for everything else */
  @import url('https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i|Roboto:100,300,400,500,700,900&display=swap');
  /* Use Nasalization for the logo */
  @font-face{
      font-family:'Nasalization';
      src: url('@/assets/fonts/nasalization-rg-webfont.woff') format('woff');
  }

.scrolls { /* Generated by Chat GPT 3.5 */
  /* Set the height and width of the div */
  height: 100%; /* You can adjust the height as needed */
  width: 100%; /* Adjust the width as needed */

  /* Add a border and padding for better visualization */
  border: 1px solid #ccc;
  padding: 10px;

  /* Enable vertical scrolling */
  overflow-y: auto; /* This will show vertical scrollbar if content exceeds height */

  /* Optional: Add a scrollbar to the right for visual consistency */
  scrollbar-width: thin; /* For Firefox */
  scrollbar-color: #888 #f5f5f5; /* For Firefox */
}

/* Optional: Styling for webkit-based browsers (Chrome, Safari, etc.) */
.scrollable-div::-webkit-scrollbar {
  width: 8px; /* Adjust the width of the scrollbar */
}

.scrollable-div::-webkit-scrollbar-track {
  background: #f5f5f5; /* Track color */
}

.scrollable-div::-webkit-scrollbar-thumb {
  background-color: #888; /* Thumb color */
  border-radius: 4px; /* Rounded corners for thumb */
}

  body{
    padding: 0px;
    margin: 0px;
    overflow: hidden;
  }

 .bg {
    background: url('./assets/mars-bg.jpg');
    background-size: cover;
    background-repeat: no-repeat;
    background-attachment: fixed;
    background-position: 50% 10%;
    background-color: #1e1e1e;
  }

  .orientation-portrait{
    display:none;
  }

  .orientation-landscape{
    display:block;
  }

  .orientation-logo{
    width: 256px;
    height: auto;
  }

   .app{
    width: 100vw;
    height: 100vh;
    min-width: 600px;
    //position: relative;

    display:flex;
    justify-content:center;
    align-items:center;
  }

  .v-application {
    font-family: "Open Sans", sans-serif !important;
  }

  .v-btn.v-btn--menu {
    font-family: sans-serif !important;
    cursor: pointer;
}

   @media all and (orientation: portrait){
    .orientation-portrait{
      display: flex;
      justify-content: center;
      align-items: center;
      width: 100%;
      height: 100%;
      background-color: rgba(#1e1e1e,.75);
    }

    .orientation-landscape{
      display:none;
    }
  }

</style>
