name: SIMOC Frontend Check

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      # workaround to prevent node/vite crashes during the build step
      # see https://github.com/vitejs/vite/issues/2433#issuecomment-831399876
      # assume 4GB - 512MB
      NODE_OPTIONS: '--max-old-space-size=3584'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Node Environment
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          check-latest: true
      - name: Download preset simdata
        run: |
          cd src/assets
          mkdir simdata
          cd simdata
          wget -r -nH --cut-dirs=2 --no-parent --accept="*.json" -erobots=off -q https://simoc.space/download/simdata/
          ls
      - name: Download skybox
        run: |
          cd src/assets
          mkdir skybox
          cd skybox
          wget -r -nH --cut-dirs=2 --no-parent --accept="*.jpg" -erobots=off -q https://simoc.space/download/skybox/
          ls
      - name: Download models
        run: |
          cd src/assets
          mkdir models
          cd models
          wget -r -nH --cut-dirs=2 --no-parent --accept="*.glb" -erobots=off -q https://simoc.space/download/models/
          ls
      - name: npm install
        run: |
          npm install --no-fund --no-audit -g npm@latest
          npm install --no-fund
      - name: Print info
        run: |
          echo "Current branch: $GITHUB_HEAD_REF"
          echo "node $(node --version); npm $(npm --version)"
      - name: Build
        run: npm run build --if-present
      - name: Test
        run: npm run test --if-present
      - name: Lint
        run: npm run lint -- --no-fix
      # To avoid hitting the artifact quota,
      # disable the next two steps for now.
      # The artifact doesn't seem to be used anyway.
#     - name: Create Frontend Artifacts
#       run: tar -cvf frontend_dist.tar dist/
#     - name: Save Frontend Artifacts
#       uses: actions/upload-artifact@v2
#       with:
#         name: dist-archive
#         path: frontend_dist.tar
      # This step can be used to notify the backend
      # that the frontend changed.  The backend can
      # then listen to a repository_dispatch event
      # and automatically build and deploy the
      # changes.  Backend deployment is triggered
      # manually now, so this step is disabled too.
#     - name: Backend Repository Dispatch
#       uses: peter-evans/repository-dispatch@v1
#       with:
#         token: ${{ secrets.ACCESS_TOKEN }}
#         repository: overthesun/simoc
#         event-type: frontend-update-prod
#         client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
